<?php

if ( ! defined( 'ABSPATH' ) ) exit;

if(function_exists( 'Vc_Manager' ) ) { 


    /* Visual composer addons custom fonts (Flaticon)
    =====================================================*/
    function dustrial_add_new_icon_set_to_iconbox( ) {
        $param = WPBMap::getParam( 'vc_icon', 'type' );
        $param['value'][__( 'Flaticons', 'total' )] = 'flaticon';
        vc_update_shortcode_param( 'vc_icon', $param );
    }
    add_filter( 'init', 'dustrial_add_new_icon_set_to_iconbox', 40 );
    // Add font picker setting to icon box module when you select your font family from the dropdown
    function dustrial_add_font_picker() {
        vc_add_param( 'vc_icon', array(
                'type' => 'iconpicker',
                'heading' => esc_html__( 'Icon', 'total' ),
                'param_name' => 'icon_flaticon',
                'settings' => array(
                    'emptyIcon' => true,
                    'type' => 'flaticon',
                    'iconsPerPage' => 200,
                ),
                'dependency' => array(
                    'element' => 'type',
                    'value' => 'flaticon',
                ),
            )
        );
    }
    add_filter( 'vc_after_init', 'dustrial_add_font_picker', 40 );


    /* Visual composer addons custom fonts
    =====================================================*/
    function dustrial_add_new_fwicon_set_to_iconbox( ) {
        $param = WPBMap::getParam( 'vc_icon', 'type' );
        $param['value'][__( 'Font Awesome 4', 'total' )] = 'fontawesome4';
        vc_update_shortcode_param( 'vc_icon', $param );
    }
    add_filter( 'init', 'dustrial_add_new_fwicon_set_to_iconbox', 50 );
    // Add font picker setting to icon box module when you select your font family from the dropdown
    function dustrial_add_faw_font_picker() {
        vc_add_param( 'vc_icon', array(
            'type' => 'iconpicker',
            'heading' => esc_html__( 'Icon', 'total' ),
            'param_name' => 'icon_fontawesome4',
            'settings' => array(
                'emptyIcon' => true,
                'type' => 'fontawesome4',
                'iconsPerPage' => 200,
            ),
            'dependency' => array(
                'element' => 'type',
                'value' => 'fontawesome4',
            ),
        )
      );
    }
    add_filter( 'vc_after_init', 'dustrial_add_faw_font_picker', 50 );

}


// Add array of your fonts so they can be displayed in the font selector
function dustrial_icon_array($icons) {
    $flaticons = array(
        array('dustrial-icon flaticon-factory-1' => 'factory'),
        array('dustrial-icon flaticon-tree' => 'tree'),
        array('dustrial-icon flaticon-handout' => 'handout'),
        array('dustrial-icon flaticon-train' => 'train'),
        array('dustrial-icon flaticon-machinery' => 'machinery'),
        array('dustrial-icon flaticon-tractor' => 'tractor'),
        array('dustrial-icon flaticon-solution' => 'solution'),
        array('dustrial-icon flaticon-wheel' => 'wheel'),
        array('dustrial-icon flaticon-gloves' => 'gloves'),
        array('dustrial-icon flaticon-truck' => 'truck'),
        array('dustrial-icon flaticon-reward' => 'reward'),
        array('dustrial-icon flaticon-travel' => 'travel'),
        array('dustrial-icon flaticon-factory' => 'factory'),
        array('dustrial-icon flaticon-analytics' => 'analytics'),
        array('dustrial-icon flaticon-crop' => 'crop'),
        array('dustrial-icon flaticon-maps-and-location' => 'maps-and-location'),
        array('dustrial-icon flaticon-plus' => 'plus'),
        array('dustrial-icon flaticon-right-arrow' => 'right-arrow'),
        array('dustrial-icon flaticon-gear' => 'gear'),
        array('dustrial-icon flaticon-motor' => 'motor'),
        array('dustrial-icon flaticon-flight' => 'flight'),
        array('dustrial-icon flaticon-ship' => 'ship'),
        array('dustrial-icon flaticon-green-energy' => 'green-energy'),
        array('dustrial-icon flaticon-machine' => 'machine'),
        array('dustrial-icon flaticon-oil-platform' => 'oil-platform'),
        array('dustrial-icon flaticon-concrete' => 'concrete'),
        array('dustrial-icon flaticon-cogwheel' => 'cogwheel'),
        array('dustrial-icon flaticon-piston' => 'piston')
    );
    return array_merge( $icons, $flaticons );
}
add_filter( 'vc_iconpicker-type-flaticon', 'dustrial_icon_array' );

// Add array of your fonts so they can be displayed in the font selector
function dustrial_icon_faw_array($icons) {

    // $stroke->getReadableNames();

    $faw4 = array(
        array( 'dustrial-icon fa fa-500px' => '500px' ),
        array( 'dustrial-icon fa fa-address-book' => 'address-book' ),
        array( 'dustrial-icon fa fa-address-book-o' => 'address-book-o' ),
        array( 'dustrial-icon fa fa-address-card' => 'address-card' ),
        array( 'dustrial-icon fa fa-address-card-o' => 'address-card-o' ),
        array( 'dustrial-icon fa fa-adjust' => 'adjust' ),
        array( 'dustrial-icon fa fa-adn' => 'adn' ),
        array( 'dustrial-icon fa fa-align-center' => 'align-center' ),
        array( 'dustrial-icon fa fa-align-justify' => 'align-justify' ),
        array( 'dustrial-icon fa fa-align-left' => 'align-left' ),
        array( 'dustrial-icon fa fa-align-right' => 'align-right' ),
        array( 'dustrial-icon fa fa-amazon' => 'amazon' ),
        array( 'dustrial-icon fa fa-ambulance' => 'ambulance' ),
        array( 'dustrial-icon fa fa-american-sign-language-interpreting' => 'american-sign-language-interpreting' ),
        array( 'dustrial-icon fa fa-anchor' => 'anchor' ),
        array( 'dustrial-icon fa fa-android' => 'android' ),
        array( 'dustrial-icon fa fa-angellist' => 'angellist' ),
        array( 'dustrial-icon fa fa-angle-double-down' => 'angle-double-down' ),
        array( 'dustrial-icon fa fa-angle-double-left' => 'angle-double-left' ),
        array( 'dustrial-icon fa fa-angle-double-right' => 'angle-double-right' ),
        array( 'dustrial-icon fa fa-angle-double-up' => 'angle-double-up' ),
        array( 'dustrial-icon fa fa-angle-down' => 'angle-down' ),
        array( 'dustrial-icon fa fa-angle-left' => 'angle-left' ),
        array( 'dustrial-icon fa fa-angle-right' => 'angle-right' ),
        array( 'dustrial-icon fa fa-angle-up' => 'angle-up' ),
        array( 'dustrial-icon fa fa-apple' => 'apple' ),
        array( 'dustrial-icon fa fa-archive' => 'archive' ),
        array( 'dustrial-icon fa fa-area-chart' => 'area-chart' ),
        array( 'dustrial-icon fa fa-arrow-circle-down' => 'arrow-circle-down' ),
        array( 'dustrial-icon fa fa-arrow-circle-left' => 'arrow-circle-left' ),
        array( 'dustrial-icon fa fa-arrow-circle-o-down' => 'arrow-circle-o-down' ),
        array( 'dustrial-icon fa fa-arrow-circle-o-left' => 'arrow-circle-o-left' ),
        array( 'dustrial-icon fa fa-arrow-circle-o-right' => 'arrow-circle-o-right' ),
        array( 'dustrial-icon fa fa-arrow-circle-o-up' => 'arrow-circle-o-up' ),
        array( 'dustrial-icon fa fa-arrow-circle-right' => 'arrow-circle-right' ),
        array( 'dustrial-icon fa fa-arrow-circle-up' => 'arrow-circle-up' ),
        array( 'dustrial-icon fa fa-arrow-down' => 'arrow-down' ),
        array( 'dustrial-icon fa fa-arrow-left' => 'arrow-left' ),
        array( 'dustrial-icon fa fa-arrow-right' => 'arrow-right' ),
        array( 'dustrial-icon fa fa-arrow-up' => 'arrow-up' ),
        array( 'dustrial-icon fa fa-arrows' => 'arrows' ),
        array( 'dustrial-icon fa fa-arrows-alt' => 'arrows-alt' ),
        array( 'dustrial-icon fa fa-arrows-h' => 'arrows-h' ),
        array( 'dustrial-icon fa fa-arrows-v' => 'arrows-v' ),
        array( 'dustrial-icon fa fa-asl-interpreting' => 'asl-interpreting' ),
        array( 'dustrial-icon fa fa-assistive-listening-systems' => 'assistive-listening-systems' ),
        array( 'dustrial-icon fa fa-asterisk' => 'asterisk' ),
        array( 'dustrial-icon fa fa-at' => 'at' ),
        array( 'dustrial-icon fa fa-audio-description' => 'audio-description' ),
        array( 'dustrial-icon fa fa-automobile' => 'automobile' ),
        array( 'dustrial-icon fa fa-backward' => 'backward' ),
        array( 'dustrial-icon fa fa-balance-scale' => 'balance-scale' ),
        array( 'dustrial-icon fa fa-ban' => 'ban' ),
        array( 'dustrial-icon fa fa-bandcamp' => 'bandcamp' ),
        array( 'dustrial-icon fa fa-bank' => 'bank' ),
        array( 'dustrial-icon fa fa-bar-chart' => 'bar-chart' ),
        array( 'dustrial-icon fa fa-bar-chart-o' => 'bar-chart-o' ),
        array( 'dustrial-icon fa fa-barcode' => 'barcode' ),
        array( 'dustrial-icon fa fa-bars' => 'bars' ),
        array( 'dustrial-icon fa fa-bath' => 'bath' ),
        array( 'dustrial-icon fa fa-bathtub' => 'bathtub' ),
        array( 'dustrial-icon fa fa-battery' => 'battery' ),
        array( 'dustrial-icon fa fa-battery-0' => 'battery-0' ),
        array( 'dustrial-icon fa fa-battery-1' => 'battery-1' ),
        array( 'dustrial-icon fa fa-battery-2' => 'battery-2' ),
        array( 'dustrial-icon fa fa-battery-3' => 'battery-3' ),
        array( 'dustrial-icon fa fa-battery-4' => 'battery-4' ),
        array( 'dustrial-icon fa fa-battery-empty' => 'battery-empty' ),
        array( 'dustrial-icon fa fa-battery-full' => 'battery-full' ),
        array( 'dustrial-icon fa fa-battery-half' => 'battery-half' ),
        array( 'dustrial-icon fa fa-battery-quarter' => 'battery-quarter' ),
        array( 'dustrial-icon fa fa-battery-three-quarters' => 'battery-three-quarters' ),
        array( 'dustrial-icon fa fa-bed' => 'bed' ),
        array( 'dustrial-icon fa fa-beer' => 'beer' ),
        array( 'dustrial-icon fa fa-behance' => 'behance' ),
        array( 'dustrial-icon fa fa-behance-square' => 'behance-square' ),
        array( 'dustrial-icon fa fa-bell' => 'bell' ),
        array( 'dustrial-icon fa fa-bell-o' => 'bell-o' ),
        array( 'dustrial-icon fa fa-bell-slash' => 'bell-slash' ),
        array( 'dustrial-icon fa fa-bell-slash-o' => 'bell-slash-o' ),
        array( 'dustrial-icon fa fa-bicycle' => 'bicycle' ),
        array( 'dustrial-icon fa fa-binoculars' => 'binoculars' ),
        array( 'dustrial-icon fa fa-birthday-cake' => 'birthday-cake' ),
        array( 'dustrial-icon fa fa-bitbucket' => 'bitbucket' ),
        array( 'dustrial-icon fa fa-bitbucket-square' => 'bitbucket-square' ),
        array( 'dustrial-icon fa fa-bitcoin' => 'bitcoin' ),
        array( 'dustrial-icon fa fa-black-tie' => 'black-tie' ),
        array( 'dustrial-icon fa fa-blind' => 'blind' ),
        array( 'dustrial-icon fa fa-bluetooth' => 'bluetooth' ),
        array( 'dustrial-icon fa fa-bluetooth-b' => 'bluetooth-b' ),
        array( 'dustrial-icon fa fa-bold' => 'bold' ),
        array( 'dustrial-icon fa fa-bolt' => 'bolt' ),
        array( 'dustrial-icon fa fa-bomb' => 'bomb' ),
        array( 'dustrial-icon fa fa-book' => 'book' ),
        array( 'dustrial-icon fa fa-bookmark' => 'bookmark' ),
        array( 'dustrial-icon fa fa-bookmark-o' => 'bookmark-o' ),
        array( 'dustrial-icon fa fa-braille' => 'braille' ),
        array( 'dustrial-icon fa fa-briefcase' => 'briefcase' ),
        array( 'dustrial-icon fa fa-btc' => 'btc' ),
        array( 'dustrial-icon fa fa-bug' => 'bug' ),
        array( 'dustrial-icon fa fa-building' => 'building' ),
        array( 'dustrial-icon fa fa-building-o' => 'building-o' ),
        array( 'dustrial-icon fa fa-bullhorn' => 'bullhorn' ),
        array( 'dustrial-icon fa fa-bullseye' => 'bullseye' ),
        array( 'dustrial-icon fa fa-bus' => 'bus' ),
        array( 'dustrial-icon fa fa-buysellads' => 'buysellads' ),
        array( 'dustrial-icon fa fa-cab' => 'cab' ),
        array( 'dustrial-icon fa fa-calculator' => 'calculator' ),
        array( 'dustrial-icon fa fa-calendar' => 'calendar' ),
        array( 'dustrial-icon fa fa-calendar-check-o' => 'calendar-check-o' ),
        array( 'dustrial-icon fa fa-calendar-minus-o' => 'calendar-minus-o' ),
        array( 'dustrial-icon fa fa-calendar-o' => 'calendar-o' ),
        array( 'dustrial-icon fa fa-calendar-plus-o' => 'calendar-plus-o' ),
        array( 'dustrial-icon fa fa-calendar-times-o' => 'calendar-times-o' ),
        array( 'dustrial-icon fa fa-camera' => 'camera' ),
        array( 'dustrial-icon fa fa-camera-retro' => 'camera-retro' ),
        array( 'dustrial-icon fa fa-car' => 'car' ),
        array( 'dustrial-icon fa fa-caret-down' => 'caret-down' ),
        array( 'dustrial-icon fa fa-caret-left' => 'caret-left' ),
        array( 'dustrial-icon fa fa-caret-right' => 'caret-right' ),
        array( 'dustrial-icon fa fa-caret-square-o-down' => 'caret-square-o-down' ),
        array( 'dustrial-icon fa fa-caret-square-o-left' => 'caret-square-o-left' ),
        array( 'dustrial-icon fa fa-caret-square-o-right' => 'caret-square-o-right' ),
        array( 'dustrial-icon fa fa-caret-square-o-up' => 'caret-square-o-up' ),
        array( 'dustrial-icon fa fa-caret-up' => 'caret-up' ),
        array( 'dustrial-icon fa fa-cart-arrow-down' => 'cart-arrow-down' ),
        array( 'dustrial-icon fa fa-cart-plus' => 'cart-plus' ),
        array( 'dustrial-icon fa fa-cc' => 'cc' ),
        array( 'dustrial-icon fa fa-cc-amex' => 'cc-amex' ),
        array( 'dustrial-icon fa fa-cc-diners-club' => 'cc-diners-club' ),
        array( 'dustrial-icon fa fa-cc-discover' => 'cc-discover' ),
        array( 'dustrial-icon fa fa-cc-jcb' => 'cc-jcb' ),
        array( 'dustrial-icon fa fa-cc-mastercard' => 'cc-mastercard' ),
        array( 'dustrial-icon fa fa-cc-paypal' => 'cc-paypal' ),
        array( 'dustrial-icon fa fa-cc-stripe' => 'cc-stripe' ),
        array( 'dustrial-icon fa fa-cc-visa' => 'cc-visa' ),
        array( 'dustrial-icon fa fa-certificate' => 'certificate' ),
        array( 'dustrial-icon fa fa-chain' => 'chain' ),
        array( 'dustrial-icon fa fa-chain-broken' => 'chain-broken' ),
        array( 'dustrial-icon fa fa-check' => 'check' ),
        array( 'dustrial-icon fa fa-check-circle' => 'check-circle' ),
        array( 'dustrial-icon fa fa-check-circle-o' => 'check-circle-o' ),
        array( 'dustrial-icon fa fa-check-square' => 'check-square' ),
        array( 'dustrial-icon fa fa-check-square-o' => 'check-square-o' ),
        array( 'dustrial-icon fa fa-chevron-circle-down' => 'chevron-circle-down' ),
        array( 'dustrial-icon fa fa-chevron-circle-left' => 'chevron-circle-left' ),
        array( 'dustrial-icon fa fa-chevron-circle-right' => 'chevron-circle-right' ),
        array( 'dustrial-icon fa fa-chevron-circle-up' => 'chevron-circle-up' ),
        array( 'dustrial-icon fa fa-chevron-down' => 'chevron-down' ),
        array( 'dustrial-icon fa fa-chevron-left' => 'chevron-left' ),
        array( 'dustrial-icon fa fa-chevron-right' => 'chevron-right' ),
        array( 'dustrial-icon fa fa-chevron-up' => 'chevron-up' ),
        array( 'dustrial-icon fa fa-child' => 'child' ),
        array( 'dustrial-icon fa fa-chrome' => 'chrome' ),
        array( 'dustrial-icon fa fa-circle' => 'circle' ),
        array( 'dustrial-icon fa fa-circle-o' => 'circle-o' ),
        array( 'dustrial-icon fa fa-circle-o-notch' => 'circle-o-notch' ),
        array( 'dustrial-icon fa fa-circle-thin' => 'circle-thin' ),
        array( 'dustrial-icon fa fa-clipboard' => 'clipboard' ),
        array( 'dustrial-icon fa fa-clock-o' => 'clock-o' ),
        array( 'dustrial-icon fa fa-clone' => 'clone' ),
        array( 'dustrial-icon fa fa-close' => 'close' ),
        array( 'dustrial-icon fa fa-cloud' => 'cloud' ),
        array( 'dustrial-icon fa fa-cloud-download' => 'cloud-download' ),
        array( 'dustrial-icon fa fa-cloud-upload' => 'cloud-upload' ),
        array( 'dustrial-icon fa fa-cny' => 'cny' ),
        array( 'dustrial-icon fa fa-code' => 'code' ),
        array( 'dustrial-icon fa fa-code-fork' => 'code-fork' ),
        array( 'dustrial-icon fa fa-codepen' => 'codepen' ),
        array( 'dustrial-icon fa fa-codiepie' => 'codiepie' ),
        array( 'dustrial-icon fa fa-coffee' => 'coffee' ),
        array( 'dustrial-icon fa fa-cog' => 'cog' ),
        array( 'dustrial-icon fa fa-cogs' => 'cogs' ),
        array( 'dustrial-icon fa fa-columns' => 'columns' ),
        array( 'dustrial-icon fa fa-comment' => 'comment' ),
        array( 'dustrial-icon fa fa-comment-o' => 'comment-o' ),
        array( 'dustrial-icon fa fa-commenting' => 'commenting' ),
        array( 'dustrial-icon fa fa-commenting-o' => 'commenting-o' ),
        array( 'dustrial-icon fa fa-comments' => 'comments' ),
        array( 'dustrial-icon fa fa-comments-o' => 'comments-o' ),
        array( 'dustrial-icon fa fa-compass' => 'compass' ),
        array( 'dustrial-icon fa fa-compress' => 'compress' ),
        array( 'dustrial-icon fa fa-connectdevelop' => 'connectdevelop' ),
        array( 'dustrial-icon fa fa-contao' => 'contao' ),
        array( 'dustrial-icon fa fa-copy' => 'copy' ),
        array( 'dustrial-icon fa fa-copyright' => 'copyright' ),
        array( 'dustrial-icon fa fa-creative-commons' => 'creative-commons' ),
        array( 'dustrial-icon fa fa-credit-card' => 'credit-card' ),
        array( 'dustrial-icon fa fa-credit-card-alt' => 'credit-card-alt' ),
        array( 'dustrial-icon fa fa-crop' => 'crop' ),
        array( 'dustrial-icon fa fa-crosshairs' => 'crosshairs' ),
        array( 'dustrial-icon fa fa-css3' => 'css3' ),
        array( 'dustrial-icon fa fa-cube' => 'cube' ),
        array( 'dustrial-icon fa fa-cubes' => 'cubes' ),
        array( 'dustrial-icon fa fa-cut' => 'cut' ),
        array( 'dustrial-icon fa fa-cutlery' => 'cutlery' ),
        array( 'dustrial-icon fa fa-dashboard' => 'dashboard' ),
        array( 'dustrial-icon fa fa-dashcube' => 'dashcube' ),
        array( 'dustrial-icon fa fa-database' => 'database' ),
        array( 'dustrial-icon fa fa-deaf' => 'deaf' ),
        array( 'dustrial-icon fa fa-deafness' => 'deafness' ),
        array( 'dustrial-icon fa fa-dedent' => 'dedent' ),
        array( 'dustrial-icon fa fa-delicious' => 'delicious' ),
        array( 'dustrial-icon fa fa-desktop' => 'desktop' ),
        array( 'dustrial-icon fa fa-deviantart' => 'deviantart' ),
        array( 'dustrial-icon fa fa-diamond' => 'diamond' ),
        array( 'dustrial-icon fa fa-digg' => 'digg' ),
        array( 'dustrial-icon fa fa-dollar' => 'dollar' ),
        array( 'dustrial-icon fa fa-dot-circle-o' => 'dot-circle-o' ),
        array( 'dustrial-icon fa fa-download' => 'download' ),
        array( 'dustrial-icon fa fa-dribbble' => 'dribbble' ),
        array( 'dustrial-icon fa fa-drivers-license' => 'drivers-license' ),
        array( 'dustrial-icon fa fa-drivers-license-o' => 'drivers-license-o' ),
        array( 'dustrial-icon fa fa-dropbox' => 'dropbox' ),
        array( 'dustrial-icon fa fa-drupal' => 'drupal' ),
        array( 'dustrial-icon fa fa-edge' => 'edge' ),
        array( 'dustrial-icon fa fa-edit' => 'edit' ),
        array( 'dustrial-icon fa fa-eercast' => 'eercast' ),
        array( 'dustrial-icon fa fa-eject' => 'eject' ),
        array( 'dustrial-icon fa fa-ellipsis-h' => 'ellipsis-h' ),
        array( 'dustrial-icon fa fa-ellipsis-v' => 'ellipsis-v' ),
        array( 'dustrial-icon fa fa-empire' => 'empire' ),
        array( 'dustrial-icon fa fa-envelope' => 'envelope' ),
        array( 'dustrial-icon fa fa-envelope-o' => 'envelope-o' ),
        array( 'dustrial-icon fa fa-envelope-open' => 'envelope-open' ),
        array( 'dustrial-icon fa fa-envelope-open-o' => 'envelope-open-o' ),
        array( 'dustrial-icon fa fa-envelope-square' => 'envelope-square' ),
        array( 'dustrial-icon fa fa-envira' => 'envira' ),
        array( 'dustrial-icon fa fa-eraser' => 'eraser' ),
        array( 'dustrial-icon fa fa-etsy' => 'etsy' ),
        array( 'dustrial-icon fa fa-eur' => 'eur' ),
        array( 'dustrial-icon fa fa-euro' => 'euro' ),
        array( 'dustrial-icon fa fa-exchange' => 'exchange' ),
        array( 'dustrial-icon fa fa-exclamation' => 'exclamation' ),
        array( 'dustrial-icon fa fa-exclamation-circle' => 'exclamation-circle' ),
        array( 'dustrial-icon fa fa-exclamation-triangle' => 'exclamation-triangle' ),
        array( 'dustrial-icon fa fa-expand' => 'expand' ),
        array( 'dustrial-icon fa fa-expeditedssl' => 'expeditedssl' ),
        array( 'dustrial-icon fa fa-external-link' => 'external-link' ),
        array( 'dustrial-icon fa fa-external-link-square' => 'external-link-square' ),
        array( 'dustrial-icon fa fa-eye' => 'eye' ),
        array( 'dustrial-icon fa fa-eye-slash' => 'eye-slash' ),
        array( 'dustrial-icon fa fa-eyedropper' => 'eyedropper' ),
        array( 'dustrial-icon fa fa-fa' => 'fa' ),
        array( 'dustrial-icon fa fa-facebook' => 'facebook' ),
        array( 'dustrial-icon fa fa-facebook-f' => 'facebook-f' ),
        array( 'dustrial-icon fa fa-facebook-official' => 'facebook-official' ),
        array( 'dustrial-icon fa fa-facebook-square' => 'facebook-square' ),
        array( 'dustrial-icon fa fa-fast-backward' => 'fast-backward' ),
        array( 'dustrial-icon fa fa-fast-forward' => 'fast-forward' ),
        array( 'dustrial-icon fa fa-fax' => 'fax' ),
        array( 'dustrial-icon fa fa-feed' => 'feed' ),
        array( 'dustrial-icon fa fa-female' => 'female' ),
        array( 'dustrial-icon fa fa-fighter-jet' => 'fighter-jet' ),
        array( 'dustrial-icon fa fa-file' => 'file' ),
        array( 'dustrial-icon fa fa-file-archive-o' => 'file-archive-o' ),
        array( 'dustrial-icon fa fa-file-audio-o' => 'file-audio-o' ),
        array( 'dustrial-icon fa fa-file-code-o' => 'file-code-o' ),
        array( 'dustrial-icon fa fa-file-excel-o' => 'file-excel-o' ),
        array( 'dustrial-icon fa fa-file-image-o' => 'file-image-o' ),
        array( 'dustrial-icon fa fa-file-movie-o' => 'file-movie-o' ),
        array( 'dustrial-icon fa fa-file-o' => 'file-o' ),
        array( 'dustrial-icon fa fa-file-pdf-o' => 'file-pdf-o' ),
        array( 'dustrial-icon fa fa-file-photo-o' => 'file-photo-o' ),
        array( 'dustrial-icon fa fa-file-picture-o' => 'file-picture-o' ),
        array( 'dustrial-icon fa fa-file-powerpoint-o' => 'file-powerpoint-o' ),
        array( 'dustrial-icon fa fa-file-sound-o' => 'file-sound-o' ),
        array( 'dustrial-icon fa fa-file-text' => 'file-text' ),
        array( 'dustrial-icon fa fa-file-text-o' => 'file-text-o' ),
        array( 'dustrial-icon fa fa-file-video-o' => 'file-video-o' ),
        array( 'dustrial-icon fa fa-file-word-o' => 'file-word-o' ),
        array( 'dustrial-icon fa fa-file-zip-o' => 'file-zip-o' ),
        array( 'dustrial-icon fa fa-files-o' => 'files-o' ),
        array( 'dustrial-icon fa fa-film' => 'film' ),
        array( 'dustrial-icon fa fa-filter' => 'filter' ),
        array( 'dustrial-icon fa fa-fire' => 'fire' ),
        array( 'dustrial-icon fa fa-fire-extinguisher' => 'fire-extinguisher' ),
        array( 'dustrial-icon fa fa-firefox' => 'firefox' ),
        array( 'dustrial-icon fa fa-first-order' => 'first-order' ),
        array( 'dustrial-icon fa fa-flag' => 'flag' ),
        array( 'dustrial-icon fa fa-flag-checkered' => 'flag-checkered' ),
        array( 'dustrial-icon fa fa-flag-o' => 'flag-o' ),
        array( 'dustrial-icon fa fa-flash' => 'flash' ),
        array( 'dustrial-icon fa fa-flask' => 'flask' ),
        array( 'dustrial-icon fa fa-flickr' => 'flickr' ),
        array( 'dustrial-icon fa fa-floppy-o' => 'floppy-o' ),
        array( 'dustrial-icon fa fa-folder' => 'folder' ),
        array( 'dustrial-icon fa fa-folder-o' => 'folder-o' ),
        array( 'dustrial-icon fa fa-folder-open' => 'folder-open' ),
        array( 'dustrial-icon fa fa-folder-open-o' => 'folder-open-o' ),
        array( 'dustrial-icon fa fa-font' => 'font' ),
        array( 'dustrial-icon fa fa-font-awesome' => 'font-awesome' ),
        array( 'dustrial-icon fa fa-fonticons' => 'fonticons' ),
        array( 'dustrial-icon fa fa-fort-awesome' => 'fort-awesome' ),
        array( 'dustrial-icon fa fa-forumbee' => 'forumbee' ),
        array( 'dustrial-icon fa fa-forward' => 'forward' ),
        array( 'dustrial-icon fa fa-foursquare' => 'foursquare' ),
        array( 'dustrial-icon fa fa-free-code-camp' => 'free-code-camp' ),
        array( 'dustrial-icon fa fa-frown-o' => 'frown-o' ),
        array( 'dustrial-icon fa fa-futbol-o' => 'futbol-o' ),
        array( 'dustrial-icon fa fa-gamepad' => 'gamepad' ),
        array( 'dustrial-icon fa fa-gavel' => 'gavel' ),
        array( 'dustrial-icon fa fa-gbp' => 'gbp' ),
        array( 'dustrial-icon fa fa-ge' => 'ge' ),
        array( 'dustrial-icon fa fa-gear' => 'gear' ),
        array( 'dustrial-icon fa fa-gears' => 'gears' ),
        array( 'dustrial-icon fa fa-genderless' => 'genderless' ),
        array( 'dustrial-icon fa fa-get-pocket' => 'get-pocket' ),
        array( 'dustrial-icon fa fa-gg' => 'gg' ),
        array( 'dustrial-icon fa fa-gg-circle' => 'gg-circle' ),
        array( 'dustrial-icon fa fa-gift' => 'gift' ),
        array( 'dustrial-icon fa fa-git' => 'git' ),
        array( 'dustrial-icon fa fa-git-square' => 'git-square' ),
        array( 'dustrial-icon fa fa-github' => 'github' ),
        array( 'dustrial-icon fa fa-github-alt' => 'github-alt' ),
        array( 'dustrial-icon fa fa-github-square' => 'github-square' ),
        array( 'dustrial-icon fa fa-gitlab' => 'gitlab' ),
        array( 'dustrial-icon fa fa-gittip' => 'gittip' ),
        array( 'dustrial-icon fa fa-glass' => 'glass' ),
        array( 'dustrial-icon fa fa-glide' => 'glide' ),
        array( 'dustrial-icon fa fa-glide-g' => 'glide-g' ),
        array( 'dustrial-icon fa fa-globe' => 'globe' ),
        array( 'dustrial-icon fa fa-google' => 'google' ),
        array( 'dustrial-icon fa fa-google-plus' => 'google-plus' ),
        array( 'dustrial-icon fa fa-google-plus-circle' => 'google-plus-circle' ),
        array( 'dustrial-icon fa fa-google-plus-official' => 'google-plus-official' ),
        array( 'dustrial-icon fa fa-google-plus-square' => 'google-plus-square' ),
        array( 'dustrial-icon fa fa-google-wallet' => 'google-wallet' ),
        array( 'dustrial-icon fa fa-graduation-cap' => 'graduation-cap' ),
        array( 'dustrial-icon fa fa-gratipay' => 'gratipay' ),
        array( 'dustrial-icon fa fa-grav' => 'grav' ),
        array( 'dustrial-icon fa fa-group' => 'group' ),
        array( 'dustrial-icon fa fa-h-square' => 'h-square' ),
        array( 'dustrial-icon fa fa-hacker-news' => 'hacker-news' ),
        array( 'dustrial-icon fa fa-hand-grab-o' => 'hand-grab-o' ),
        array( 'dustrial-icon fa fa-hand-lizard-o' => 'hand-lizard-o' ),
        array( 'dustrial-icon fa fa-hand-o-down' => 'hand-o-down' ),
        array( 'dustrial-icon fa fa-hand-o-left' => 'hand-o-left' ),
        array( 'dustrial-icon fa fa-hand-o-right' => 'hand-o-right' ),
        array( 'dustrial-icon fa fa-hand-o-up' => 'hand-o-up' ),
        array( 'dustrial-icon fa fa-hand-paper-o' => 'hand-paper-o' ),
        array( 'dustrial-icon fa fa-hand-peace-o' => 'hand-peace-o' ),
        array( 'dustrial-icon fa fa-hand-pointer-o' => 'hand-pointer-o' ),
        array( 'dustrial-icon fa fa-hand-rock-o' => 'hand-rock-o' ),
        array( 'dustrial-icon fa fa-hand-scissors-o' => 'hand-scissors-o' ),
        array( 'dustrial-icon fa fa-hand-spock-o' => 'hand-spock-o' ),
        array( 'dustrial-icon fa fa-hand-stop-o' => 'hand-stop-o' ),
        array( 'dustrial-icon fa fa-handshake-o' => 'handshake-o' ),
        array( 'dustrial-icon fa fa-hard-of-hearing' => 'hard-of-hearing' ),
        array( 'dustrial-icon fa fa-hashtag' => 'hashtag' ),
        array( 'dustrial-icon fa fa-hdd-o' => 'hdd-o' ),
        array( 'dustrial-icon fa fa-header' => 'header' ),
        array( 'dustrial-icon fa fa-headphones' => 'headphones' ),
        array( 'dustrial-icon fa fa-heart' => 'heart' ),
        array( 'dustrial-icon fa fa-heart-o' => 'heart-o' ),
        array( 'dustrial-icon fa fa-heartbeat' => 'heartbeat' ),
        array( 'dustrial-icon fa fa-history' => 'history' ),
        array( 'dustrial-icon fa fa-home' => 'home' ),
        array( 'dustrial-icon fa fa-hospital-o' => 'hospital-o' ),
        array( 'dustrial-icon fa fa-hotel' => 'hotel' ),
        array( 'dustrial-icon fa fa-hourglass' => 'hourglass' ),
        array( 'dustrial-icon fa fa-hourglass-1' => 'hourglass-1' ),
        array( 'dustrial-icon fa fa-hourglass-2' => 'hourglass-2' ),
        array( 'dustrial-icon fa fa-hourglass-3' => 'hourglass-3' ),
        array( 'dustrial-icon fa fa-hourglass-end' => 'hourglass-end' ),
        array( 'dustrial-icon fa fa-hourglass-half' => 'hourglass-half' ),
        array( 'dustrial-icon fa fa-hourglass-o' => 'hourglass-o' ),
        array( 'dustrial-icon fa fa-hourglass-start' => 'hourglass-start' ),
        array( 'dustrial-icon fa fa-houzz' => 'houzz' ),
        array( 'dustrial-icon fa fa-html5' => 'html5' ),
        array( 'dustrial-icon fa fa-i-cursor' => 'i-cursor' ),
        array( 'dustrial-icon fa fa-id-badge' => 'id-badge' ),
        array( 'dustrial-icon fa fa-id-card' => 'id-card' ),
        array( 'dustrial-icon fa fa-id-card-o' => 'id-card-o' ),
        array( 'dustrial-icon fa fa-ils' => 'ils' ),
        array( 'dustrial-icon fa fa-image' => 'image' ),
        array( 'dustrial-icon fa fa-imdb' => 'imdb' ),
        array( 'dustrial-icon fa fa-inbox' => 'inbox' ),
        array( 'dustrial-icon fa fa-indent' => 'indent' ),
        array( 'dustrial-icon fa fa-industry' => 'industry' ),
        array( 'dustrial-icon fa fa-info' => 'info' ),
        array( 'dustrial-icon fa fa-info-circle' => 'info-circle' ),
        array( 'dustrial-icon fa fa-inr' => 'inr' ),
        array( 'dustrial-icon fa fa-instagram' => 'instagram' ),
        array( 'dustrial-icon fa fa-institution' => 'institution' ),
        array( 'dustrial-icon fa fa-internet-explorer' => 'internet-explorer' ),
        array( 'dustrial-icon fa fa-intersex' => 'intersex' ),
        array( 'dustrial-icon fa fa-ioxhost' => 'ioxhost' ),
        array( 'dustrial-icon fa fa-italic' => 'italic' ),
        array( 'dustrial-icon fa fa-joomla' => 'joomla' ),
        array( 'dustrial-icon fa fa-jpy' => 'jpy' ),
        array( 'dustrial-icon fa fa-jsfiddle' => 'jsfiddle' ),
        array( 'dustrial-icon fa fa-key' => 'key' ),
        array( 'dustrial-icon fa fa-keyboard-o' => 'keyboard-o' ),
        array( 'dustrial-icon fa fa-krw' => 'krw' ),
        array( 'dustrial-icon fa fa-language' => 'language' ),
        array( 'dustrial-icon fa fa-laptop' => 'laptop' ),
        array( 'dustrial-icon fa fa-lastfm' => 'lastfm' ),
        array( 'dustrial-icon fa fa-lastfm-square' => 'lastfm-square' ),
        array( 'dustrial-icon fa fa-leaf' => 'leaf' ),
        array( 'dustrial-icon fa fa-leanpub' => 'leanpub' ),
        array( 'dustrial-icon fa fa-legal' => 'legal' ),
        array( 'dustrial-icon fa fa-lemon-o' => 'lemon-o' ),
        array( 'dustrial-icon fa fa-level-down' => 'level-down' ),
        array( 'dustrial-icon fa fa-level-up' => 'level-up' ),
        array( 'dustrial-icon fa fa-life-bouy' => 'life-bouy' ),
        array( 'dustrial-icon fa fa-life-buoy' => 'life-buoy' ),
        array( 'dustrial-icon fa fa-life-ring' => 'life-ring' ),
        array( 'dustrial-icon fa fa-life-saver' => 'life-saver' ),
        array( 'dustrial-icon fa fa-lightbulb-o' => 'lightbulb-o' ),
        array( 'dustrial-icon fa fa-line-chart' => 'line-chart' ),
        array( 'dustrial-icon fa fa-link' => 'link' ),
        array( 'dustrial-icon fa fa-linkedin' => 'linkedin' ),
        array( 'dustrial-icon fa fa-linkedin-square' => 'linkedin-square' ),
        array( 'dustrial-icon fa fa-linode' => 'linode' ),
        array( 'dustrial-icon fa fa-linux' => 'linux' ),
        array( 'dustrial-icon fa fa-list' => 'list' ),
        array( 'dustrial-icon fa fa-list-alt' => 'list-alt' ),
        array( 'dustrial-icon fa fa-list-ol' => 'list-ol' ),
        array( 'dustrial-icon fa fa-list-ul' => 'list-ul' ),
        array( 'dustrial-icon fa fa-location-arrow' => 'location-arrow' ),
        array( 'dustrial-icon fa fa-lock' => 'lock' ),
        array( 'dustrial-icon fa fa-long-arrow-down' => 'long-arrow-down' ),
        array( 'dustrial-icon fa fa-long-arrow-left' => 'long-arrow-left' ),
        array( 'dustrial-icon fa fa-long-arrow-right' => 'long-arrow-right' ),
        array( 'dustrial-icon fa fa-long-arrow-up' => 'long-arrow-up' ),
        array( 'dustrial-icon fa fa-low-vision' => 'low-vision' ),
        array( 'dustrial-icon fa fa-magic' => 'magic' ),
        array( 'dustrial-icon fa fa-magnet' => 'magnet' ),
        array( 'dustrial-icon fa fa-mail-forward' => 'mail-forward' ),
        array( 'dustrial-icon fa fa-mail-reply' => 'mail-reply' ),
        array( 'dustrial-icon fa fa-mail-reply-all' => 'mail-reply-all' ),
        array( 'dustrial-icon fa fa-male' => 'male' ),
        array( 'dustrial-icon fa fa-map' => 'map' ),
        array( 'dustrial-icon fa fa-map-marker' => 'map-marker' ),
        array( 'dustrial-icon fa fa-map-o' => 'map-o' ),
        array( 'dustrial-icon fa fa-map-pin' => 'map-pin' ),
        array( 'dustrial-icon fa fa-map-signs' => 'map-signs' ),
        array( 'dustrial-icon fa fa-mars' => 'mars' ),
        array( 'dustrial-icon fa fa-mars-double' => 'mars-double' ),
        array( 'dustrial-icon fa fa-mars-stroke' => 'mars-stroke' ),
        array( 'dustrial-icon fa fa-mars-stroke-h' => 'mars-stroke-h' ),
        array( 'dustrial-icon fa fa-mars-stroke-v' => 'mars-stroke-v' ),
        array( 'dustrial-icon fa fa-maxcdn' => 'maxcdn' ),
        array( 'dustrial-icon fa fa-meanpath' => 'meanpath' ),
        array( 'dustrial-icon fa fa-medium' => 'medium' ),
        array( 'dustrial-icon fa fa-medkit' => 'medkit' ),
        array( 'dustrial-icon fa fa-meetup' => 'meetup' ),
        array( 'dustrial-icon fa fa-meh-o' => 'meh-o' ),
        array( 'dustrial-icon fa fa-mercury' => 'mercury' ),
        array( 'dustrial-icon fa fa-microchip' => 'microchip' ),
        array( 'dustrial-icon fa fa-microphone' => 'microphone' ),
        array( 'dustrial-icon fa fa-microphone-slash' => 'microphone-slash' ),
        array( 'dustrial-icon fa fa-minus' => 'minus' ),
        array( 'dustrial-icon fa fa-minus-circle' => 'minus-circle' ),
        array( 'dustrial-icon fa fa-minus-square' => 'minus-square' ),
        array( 'dustrial-icon fa fa-minus-square-o' => 'minus-square-o' ),
        array( 'dustrial-icon fa fa-mixcloud' => 'mixcloud' ),
        array( 'dustrial-icon fa fa-mobile' => 'mobile' ),
        array( 'dustrial-icon fa fa-mobile-phone' => 'mobile-phone' ),
        array( 'dustrial-icon fa fa-modx' => 'modx' ),
        array( 'dustrial-icon fa fa-money' => 'money' ),
        array( 'dustrial-icon fa fa-moon-o' => 'moon-o' ),
        array( 'dustrial-icon fa fa-mortar-board' => 'mortar-board' ),
        array( 'dustrial-icon fa fa-motorcycle' => 'motorcycle' ),
        array( 'dustrial-icon fa fa-mouse-pointer' => 'mouse-pointer' ),
        array( 'dustrial-icon fa fa-music' => 'music' ),
        array( 'dustrial-icon fa fa-navicon' => 'navicon' ),
        array( 'dustrial-icon fa fa-neuter' => 'neuter' ),
        array( 'dustrial-icon fa fa-newspaper-o' => 'newspaper-o' ),
        array( 'dustrial-icon fa fa-object-group' => 'object-group' ),
        array( 'dustrial-icon fa fa-object-ungroup' => 'object-ungroup' ),
        array( 'dustrial-icon fa fa-odnoklassniki' => 'odnoklassniki' ),
        array( 'dustrial-icon fa fa-odnoklassniki-square' => 'odnoklassniki-square' ),
        array( 'dustrial-icon fa fa-opencart' => 'opencart' ),
        array( 'dustrial-icon fa fa-openid' => 'openid' ),
        array( 'dustrial-icon fa fa-opera' => 'opera' ),
        array( 'dustrial-icon fa fa-optin-monster' => 'optin-monster' ),
        array( 'dustrial-icon fa fa-outdent' => 'outdent' ),
        array( 'dustrial-icon fa fa-pagelines' => 'pagelines' ),
        array( 'dustrial-icon fa fa-paint-brush' => 'paint-brush' ),
        array( 'dustrial-icon fa fa-paper-plane' => 'paper-plane' ),
        array( 'dustrial-icon fa fa-paper-plane-o' => 'paper-plane-o' ),
        array( 'dustrial-icon fa fa-paperclip' => 'paperclip' ),
        array( 'dustrial-icon fa fa-paragraph' => 'paragraph' ),
        array( 'dustrial-icon fa fa-paste' => 'paste' ),
        array( 'dustrial-icon fa fa-pause' => 'pause' ),
        array( 'dustrial-icon fa fa-pause-circle' => 'pause-circle' ),
        array( 'dustrial-icon fa fa-pause-circle-o' => 'pause-circle-o' ),
        array( 'dustrial-icon fa fa-paw' => 'paw' ),
        array( 'dustrial-icon fa fa-paypal' => 'paypal' ),
        array( 'dustrial-icon fa fa-pencil' => 'pencil' ),
        array( 'dustrial-icon fa fa-pencil-square' => 'pencil-square' ),
        array( 'dustrial-icon fa fa-pencil-square-o' => 'pencil-square-o' ),
        array( 'dustrial-icon fa fa-percent' => 'percent' ),
        array( 'dustrial-icon fa fa-phone' => 'phone' ),
        array( 'dustrial-icon fa fa-phone-square' => 'phone-square' ),
        array( 'dustrial-icon fa fa-photo' => 'photo' ),
        array( 'dustrial-icon fa fa-picture-o' => 'picture-o' ),
        array( 'dustrial-icon fa fa-pie-chart' => 'pie-chart' ),
        array( 'dustrial-icon fa fa-pied-piper' => 'pied-piper' ),
        array( 'dustrial-icon fa fa-pied-piper-alt' => 'pied-piper-alt' ),
        array( 'dustrial-icon fa fa-pied-piper-pp' => 'pied-piper-pp' ),
        array( 'dustrial-icon fa fa-pinterest' => 'pinterest' ),
        array( 'dustrial-icon fa fa-pinterest-p' => 'pinterest-p' ),
        array( 'dustrial-icon fa fa-pinterest-square' => 'pinterest-square' ),
        array( 'dustrial-icon fa fa-plane' => 'plane' ),
        array( 'dustrial-icon fa fa-play' => 'play' ),
        array( 'dustrial-icon fa fa-play-circle' => 'play-circle' ),
        array( 'dustrial-icon fa fa-play-circle-o' => 'play-circle-o' ),
        array( 'dustrial-icon fa fa-plug' => 'plug' ),
        array( 'dustrial-icon fa fa-plus' => 'plus' ),
        array( 'dustrial-icon fa fa-plus-circle' => 'plus-circle' ),
        array( 'dustrial-icon fa fa-plus-square' => 'plus-square' ),
        array( 'dustrial-icon fa fa-plus-square-o' => 'plus-square-o' ),
        array( 'dustrial-icon fa fa-podcast' => 'podcast' ),
        array( 'dustrial-icon fa fa-power-off' => 'power-off' ),
        array( 'dustrial-icon fa fa-print' => 'print' ),
        array( 'dustrial-icon fa fa-product-hunt' => 'product-hunt' ),
        array( 'dustrial-icon fa fa-puzzle-piece' => 'puzzle-piece' ),
        array( 'dustrial-icon fa fa-qq' => 'qq' ),
        array( 'dustrial-icon fa fa-qrcode' => 'qrcode' ),
        array( 'dustrial-icon fa fa-question' => 'question' ),
        array( 'dustrial-icon fa fa-question-circle' => 'question-circle' ),
        array( 'dustrial-icon fa fa-question-circle-o' => 'question-circle-o' ),
        array( 'dustrial-icon fa fa-quora' => 'quora' ),
        array( 'dustrial-icon fa fa-quote-left' => 'quote-left' ),
        array( 'dustrial-icon fa fa-quote-right' => 'quote-right' ),
        array( 'dustrial-icon fa fa-ra' => 'ra' ),
        array( 'dustrial-icon fa fa-random' => 'random' ),
        array( 'dustrial-icon fa fa-ravelry' => 'ravelry' ),
        array( 'dustrial-icon fa fa-rebel' => 'rebel' ),
        array( 'dustrial-icon fa fa-recycle' => 'recycle' ),
        array( 'dustrial-icon fa fa-reddit' => 'reddit' ),
        array( 'dustrial-icon fa fa-reddit-alien' => 'reddit-alien' ),
        array( 'dustrial-icon fa fa-reddit-square' => 'reddit-square' ),
        array( 'dustrial-icon fa fa-refresh' => 'refresh' ),
        array( 'dustrial-icon fa fa-registered' => 'registered' ),
        array( 'dustrial-icon fa fa-remove' => 'remove' ),
        array( 'dustrial-icon fa fa-renren' => 'renren' ),
        array( 'dustrial-icon fa fa-reorder' => 'reorder' ),
        array( 'dustrial-icon fa fa-repeat' => 'repeat' ),
        array( 'dustrial-icon fa fa-reply' => 'reply' ),
        array( 'dustrial-icon fa fa-reply-all' => 'reply-all' ),
        array( 'dustrial-icon fa fa-resistance' => 'resistance' ),
        array( 'dustrial-icon fa fa-retweet' => 'retweet' ),
        array( 'dustrial-icon fa fa-rmb' => 'rmb' ),
        array( 'dustrial-icon fa fa-road' => 'road' ),
        array( 'dustrial-icon fa fa-rocket' => 'rocket' ),
        array( 'dustrial-icon fa fa-rotate-left' => 'rotate-left' ),
        array( 'dustrial-icon fa fa-rotate-right' => 'rotate-right' ),
        array( 'dustrial-icon fa fa-rouble' => 'rouble' ),
        array( 'dustrial-icon fa fa-rss' => 'rss' ),
        array( 'dustrial-icon fa fa-rss-square' => 'rss-square' ),
        array( 'dustrial-icon fa fa-rub' => 'rub' ),
        array( 'dustrial-icon fa fa-ruble' => 'ruble' ),
        array( 'dustrial-icon fa fa-rupee' => 'rupee' ),
        array( 'dustrial-icon fa fa-s15' => 's15' ),
        array( 'dustrial-icon fa fa-safari' => 'safari' ),
        array( 'dustrial-icon fa fa-save' => 'save' ),
        array( 'dustrial-icon fa fa-scissors' => 'scissors' ),
        array( 'dustrial-icon fa fa-scribd' => 'scribd' ),
        array( 'dustrial-icon fa fa-search' => 'search' ),
        array( 'dustrial-icon fa fa-search-minus' => 'search-minus' ),
        array( 'dustrial-icon fa fa-search-plus' => 'search-plus' ),
        array( 'dustrial-icon fa fa-sellsy' => 'sellsy' ),
        array( 'dustrial-icon fa fa-send' => 'send' ),
        array( 'dustrial-icon fa fa-send-o' => 'send-o' ),
        array( 'dustrial-icon fa fa-server' => 'server' ),
        array( 'dustrial-icon fa fa-share' => 'share' ),
        array( 'dustrial-icon fa fa-share-alt' => 'share-alt' ),
        array( 'dustrial-icon fa fa-share-alt-square' => 'share-alt-square' ),
        array( 'dustrial-icon fa fa-share-square' => 'share-square' ),
        array( 'dustrial-icon fa fa-share-square-o' => 'share-square-o' ),
        array( 'dustrial-icon fa fa-shekel' => 'shekel' ),
        array( 'dustrial-icon fa fa-sheqel' => 'sheqel' ),
        array( 'dustrial-icon fa fa-shield' => 'shield' ),
        array( 'dustrial-icon fa fa-ship' => 'ship' ),
        array( 'dustrial-icon fa fa-shirtsinbulk' => 'shirtsinbulk' ),
        array( 'dustrial-icon fa fa-shopping-bag' => 'shopping-bag' ),
        array( 'dustrial-icon fa fa-shopping-basket' => 'shopping-basket' ),
        array( 'dustrial-icon fa fa-shopping-cart' => 'shopping-cart' ),
        array( 'dustrial-icon fa fa-shower' => 'shower' ),
        array( 'dustrial-icon fa fa-sign-in' => 'sign-in' ),
        array( 'dustrial-icon fa fa-sign-language' => 'sign-language' ),
        array( 'dustrial-icon fa fa-sign-out' => 'sign-out' ),
        array( 'dustrial-icon fa fa-signal' => 'signal' ),
        array( 'dustrial-icon fa fa-signing' => 'signing' ),
        array( 'dustrial-icon fa fa-simplybuilt' => 'simplybuilt' ),
        array( 'dustrial-icon fa fa-sitemap' => 'sitemap' ),
        array( 'dustrial-icon fa fa-skyatlas' => 'skyatlas' ),
        array( 'dustrial-icon fa fa-skype' => 'skype' ),
        array( 'dustrial-icon fa fa-slack' => 'slack' ),
        array( 'dustrial-icon fa fa-sliders' => 'sliders' ),
        array( 'dustrial-icon fa fa-slideshare' => 'slideshare' ),
        array( 'dustrial-icon fa fa-smile-o' => 'smile-o' ),
        array( 'dustrial-icon fa fa-snapchat' => 'snapchat' ),
        array( 'dustrial-icon fa fa-snapchat-ghost' => 'snapchat-ghost' ),
        array( 'dustrial-icon fa fa-snapchat-square' => 'snapchat-square' ),
        array( 'dustrial-icon fa fa-snowflake-o' => 'snowflake-o' ),
        array( 'dustrial-icon fa fa-soccer-ball-o' => 'soccer-ball-o' ),
        array( 'dustrial-icon fa fa-sort' => 'sort' ),
        array( 'dustrial-icon fa fa-sort-alpha-asc' => 'sort-alpha-asc' ),
        array( 'dustrial-icon fa fa-sort-alpha-desc' => 'sort-alpha-desc' ),
        array( 'dustrial-icon fa fa-sort-amount-asc' => 'sort-amount-asc' ),
        array( 'dustrial-icon fa fa-sort-amount-desc' => 'sort-amount-desc' ),
        array( 'dustrial-icon fa fa-sort-asc' => 'sort-asc' ),
        array( 'dustrial-icon fa fa-sort-desc' => 'sort-desc' ),
        array( 'dustrial-icon fa fa-sort-down' => 'sort-down' ),
        array( 'dustrial-icon fa fa-sort-numeric-asc' => 'sort-numeric-asc' ),
        array( 'dustrial-icon fa fa-sort-numeric-desc' => 'sort-numeric-desc' ),
        array( 'dustrial-icon fa fa-sort-up' => 'sort-up' ),
        array( 'dustrial-icon fa fa-soundcloud' => 'soundcloud' ),
        array( 'dustrial-icon fa fa-space-shuttle' => 'space-shuttle' ),
        array( 'dustrial-icon fa fa-spinner' => 'spinner' ),
        array( 'dustrial-icon fa fa-spoon' => 'spoon' ),
        array( 'dustrial-icon fa fa-spotify' => 'spotify' ),
        array( 'dustrial-icon fa fa-square' => 'square' ),
        array( 'dustrial-icon fa fa-square-o' => 'square-o' ),
        array( 'dustrial-icon fa fa-stack-exchange' => 'stack-exchange' ),
        array( 'dustrial-icon fa fa-stack-overflow' => 'stack-overflow' ),
        array( 'dustrial-icon fa fa-star' => 'star' ),
        array( 'dustrial-icon fa fa-star-half' => 'star-half' ),
        array( 'dustrial-icon fa fa-star-half-empty' => 'star-half-empty' ),
        array( 'dustrial-icon fa fa-star-half-full' => 'star-half-full' ),
        array( 'dustrial-icon fa fa-star-half-o' => 'star-half-o' ),
        array( 'dustrial-icon fa fa-star-o' => 'star-o' ),
        array( 'dustrial-icon fa fa-steam' => 'steam' ),
        array( 'dustrial-icon fa fa-steam-square' => 'steam-square' ),
        array( 'dustrial-icon fa fa-step-backward' => 'step-backward' ),
        array( 'dustrial-icon fa fa-step-forward' => 'step-forward' ),
        array( 'dustrial-icon fa fa-stethoscope' => 'stethoscope' ),
        array( 'dustrial-icon fa fa-sticky-note' => 'sticky-note' ),
        array( 'dustrial-icon fa fa-sticky-note-o' => 'sticky-note-o' ),
        array( 'dustrial-icon fa fa-stop' => 'stop' ),
        array( 'dustrial-icon fa fa-stop-circle' => 'stop-circle' ),
        array( 'dustrial-icon fa fa-stop-circle-o' => 'stop-circle-o' ),
        array( 'dustrial-icon fa fa-street-view' => 'street-view' ),
        array( 'dustrial-icon fa fa-strikethrough' => 'strikethrough' ),
        array( 'dustrial-icon fa fa-stumbleupon' => 'stumbleupon' ),
        array( 'dustrial-icon fa fa-stumbleupon-circle' => 'stumbleupon-circle' ),
        array( 'dustrial-icon fa fa-subscript' => 'subscript' ),
        array( 'dustrial-icon fa fa-subway' => 'subway' ),
        array( 'dustrial-icon fa fa-suitcase' => 'suitcase' ),
        array( 'dustrial-icon fa fa-sun-o' => 'sun-o' ),
        array( 'dustrial-icon fa fa-superpowers' => 'superpowers' ),
        array( 'dustrial-icon fa fa-superscript' => 'superscript' ),
        array( 'dustrial-icon fa fa-support' => 'support' ),
        array( 'dustrial-icon fa fa-table' => 'table' ),
        array( 'dustrial-icon fa fa-tablet' => 'tablet' ),
        array( 'dustrial-icon fa fa-tachometer' => 'tachometer' ),
        array( 'dustrial-icon fa fa-tag' => 'tag' ),
        array( 'dustrial-icon fa fa-tags' => 'tags' ),
        array( 'dustrial-icon fa fa-tasks' => 'tasks' ),
        array( 'dustrial-icon fa fa-taxi' => 'taxi' ),
        array( 'dustrial-icon fa fa-telegram' => 'telegram' ),
        array( 'dustrial-icon fa fa-television' => 'television' ),
        array( 'dustrial-icon fa fa-tencent-weibo' => 'tencent-weibo' ),
        array( 'dustrial-icon fa fa-terminal' => 'terminal' ),
        array( 'dustrial-icon fa fa-text-height' => 'text-height' ),
        array( 'dustrial-icon fa fa-text-width' => 'text-width' ),
        array( 'dustrial-icon fa fa-th' => 'th' ),
        array( 'dustrial-icon fa fa-th-large' => 'th-large' ),
        array( 'dustrial-icon fa fa-th-list' => 'th-list' ),
        array( 'dustrial-icon fa fa-themeisle' => 'themeisle' ),
        array( 'dustrial-icon fa fa-thermometer' => 'thermometer' ),
        array( 'dustrial-icon fa fa-thermometer-0' => 'thermometer-0' ),
        array( 'dustrial-icon fa fa-thermometer-1' => 'thermometer-1' ),
        array( 'dustrial-icon fa fa-thermometer-2' => 'thermometer-2' ),
        array( 'dustrial-icon fa fa-thermometer-3' => 'thermometer-3' ),
        array( 'dustrial-icon fa fa-thermometer-4' => 'thermometer-4' ),
        array( 'dustrial-icon fa fa-thermometer-empty' => 'thermometer-empty' ),
        array( 'dustrial-icon fa fa-thermometer-full' => 'thermometer-full' ),
        array( 'dustrial-icon fa fa-thermometer-half' => 'thermometer-half' ),
        array( 'dustrial-icon fa fa-thermometer-quarter' => 'thermometer-quarter' ),
        array( 'dustrial-icon fa fa-thermometer-three-quarters' => 'thermometer-three-quarters' ),
        array( 'dustrial-icon fa fa-thumb-tack' => 'thumb-tack' ),
        array( 'dustrial-icon fa fa-thumbs-down' => 'thumbs-down' ),
        array( 'dustrial-icon fa fa-thumbs-o-down' => 'thumbs-o-down' ),
        array( 'dustrial-icon fa fa-thumbs-o-up' => 'thumbs-o-up' ),
        array( 'dustrial-icon fa fa-thumbs-up' => 'thumbs-up' ),
        array( 'dustrial-icon fa fa-ticket' => 'ticket' ),
        array( 'dustrial-icon fa fa-times' => 'times' ),
        array( 'dustrial-icon fa fa-times-circle' => 'times-circle' ),
        array( 'dustrial-icon fa fa-times-circle-o' => 'times-circle-o' ),
        array( 'dustrial-icon fa fa-times-rectangle' => 'times-rectangle' ),
        array( 'dustrial-icon fa fa-times-rectangle-o' => 'times-rectangle-o' ),
        array( 'dustrial-icon fa fa-tint' => 'tint' ),
        array( 'dustrial-icon fa fa-toggle-down' => 'toggle-down' ),
        array( 'dustrial-icon fa fa-toggle-left' => 'toggle-left' ),
        array( 'dustrial-icon fa fa-toggle-off' => 'toggle-off' ),
        array( 'dustrial-icon fa fa-toggle-on' => 'toggle-on' ),
        array( 'dustrial-icon fa fa-toggle-right' => 'toggle-right' ),
        array( 'dustrial-icon fa fa-toggle-up' => 'toggle-up' ),
        array( 'dustrial-icon fa fa-trademark' => 'trademark' ),
        array( 'dustrial-icon fa fa-train' => 'train' ),
        array( 'dustrial-icon fa fa-transgender' => 'transgender' ),
        array( 'dustrial-icon fa fa-transgender-alt' => 'transgender-alt' ),
        array( 'dustrial-icon fa fa-trash' => 'trash' ),
        array( 'dustrial-icon fa fa-trash-o' => 'trash-o' ),
        array( 'dustrial-icon fa fa-tree' => 'tree' ),
        array( 'dustrial-icon fa fa-trello' => 'trello' ),
        array( 'dustrial-icon fa fa-tripadvisor' => 'tripadvisor' ),
        array( 'dustrial-icon fa fa-trophy' => 'trophy' ),
        array( 'dustrial-icon fa fa-truck' => 'truck' ),
        array( 'dustrial-icon fa fa-try' => 'try' ),
        array( 'dustrial-icon fa fa-tty' => 'tty' ),
        array( 'dustrial-icon fa fa-tumblr' => 'tumblr' ),
        array( 'dustrial-icon fa fa-tumblr-square' => 'tumblr-square' ),
        array( 'dustrial-icon fa fa-turkish-lira' => 'turkish-lira' ),
        array( 'dustrial-icon fa fa-tv' => 'tv' ),
        array( 'dustrial-icon fa fa-twitch' => 'twitch' ),
        array( 'dustrial-icon fa fa-twitter' => 'twitter' ),
        array( 'dustrial-icon fa fa-twitter-square' => 'twitter-square' ),
        array( 'dustrial-icon fa fa-umbrella' => 'umbrella' ),
        array( 'dustrial-icon fa fa-underline' => 'underline' ),
        array( 'dustrial-icon fa fa-undo' => 'undo' ),
        array( 'dustrial-icon fa fa-universal-access' => 'universal-access' ),
        array( 'dustrial-icon fa fa-university' => 'university' ),
        array( 'dustrial-icon fa fa-unlink' => 'unlink' ),
        array( 'dustrial-icon fa fa-unlock' => 'unlock' ),
        array( 'dustrial-icon fa fa-unlock-alt' => 'unlock-alt' ),
        array( 'dustrial-icon fa fa-unsorted' => 'unsorted' ),
        array( 'dustrial-icon fa fa-upload' => 'upload' ),
        array( 'dustrial-icon fa fa-usb' => 'usb' ),
        array( 'dustrial-icon fa fa-usd' => 'usd' ),
        array( 'dustrial-icon fa fa-user' => 'user' ),
        array( 'dustrial-icon fa fa-user-circle' => 'user-circle' ),
        array( 'dustrial-icon fa fa-user-circle-o' => 'user-circle-o' ),
        array( 'dustrial-icon fa fa-user-md' => 'user-md' ),
        array( 'dustrial-icon fa fa-user-o' => 'user-o' ),
        array( 'dustrial-icon fa fa-user-plus' => 'user-plus' ),
        array( 'dustrial-icon fa fa-user-secret' => 'user-secret' ),
        array( 'dustrial-icon fa fa-user-times' => 'user-times' ),
        array( 'dustrial-icon fa fa-users' => 'users' ),
        array( 'dustrial-icon fa fa-vcard' => 'vcard' ),
        array( 'dustrial-icon fa fa-vcard-o' => 'vcard-o' ),
        array( 'dustrial-icon fa fa-venus' => 'venus' ),
        array( 'dustrial-icon fa fa-venus-double' => 'venus-double' ),
        array( 'dustrial-icon fa fa-venus-mars' => 'venus-mars' ),
        array( 'dustrial-icon fa fa-viacoin' => 'viacoin' ),
        array( 'dustrial-icon fa fa-viadeo' => 'viadeo' ),
        array( 'dustrial-icon fa fa-viadeo-square' => 'viadeo-square' ),
        array( 'dustrial-icon fa fa-video-camera' => 'video-camera' ),
        array( 'dustrial-icon fa fa-vimeo' => 'vimeo' ),
        array( 'dustrial-icon fa fa-vimeo-square' => 'vimeo-square' ),
        array( 'dustrial-icon fa fa-vine' => 'vine' ),
        array( 'dustrial-icon fa fa-vk' => 'vk' ),
        array( 'dustrial-icon fa fa-volume-control-phone' => 'volume-control-phone' ),
        array( 'dustrial-icon fa fa-volume-down' => 'volume-down' ),
        array( 'dustrial-icon fa fa-volume-off' => 'volume-off' ),
        array( 'dustrial-icon fa fa-volume-up' => 'volume-up' ),
        array( 'dustrial-icon fa fa-warning' => 'warning' ),
        array( 'dustrial-icon fa fa-wechat' => 'wechat' ),
        array( 'dustrial-icon fa fa-weibo' => 'weibo' ),
        array( 'dustrial-icon fa fa-weixin' => 'weixin' ),
        array( 'dustrial-icon fa fa-whatsapp' => 'whatsapp' ),
        array( 'dustrial-icon fa fa-wheelchair' => 'wheelchair' ),
        array( 'dustrial-icon fa fa-wheelchair-alt' => 'wheelchair-alt' ),
        array( 'dustrial-icon fa fa-wifi' => 'wifi' ),
        array( 'dustrial-icon fa fa-wikipedia-w' => 'wikipedia-w' ),
        array( 'dustrial-icon fa fa-window-close' => 'window-close' ),
        array( 'dustrial-icon fa fa-window-close-o' => 'window-close-o' ),
        array( 'dustrial-icon fa fa-window-maximize' => 'window-maximize' ),
        array( 'dustrial-icon fa fa-window-minimize' => 'window-minimize' ),
        array( 'dustrial-icon fa fa-window-restore' => 'window-restore' ),
        array( 'dustrial-icon fa fa-windows' => 'windows' ),
        array( 'dustrial-icon fa fa-won' => 'won' ),
        array( 'dustrial-icon fa fa-wordpress' => 'wordpress' ),
        array( 'dustrial-icon fa fa-wpbeginner' => 'wpbeginner' ),
        array( 'dustrial-icon fa fa-wpexplorer' => 'wpexplorer' ),
        array( 'dustrial-icon fa fa-wpforms' => 'wpforms' ),
        array( 'dustrial-icon fa fa-wrench' => 'wrench' ),
        array( 'dustrial-icon fa fa-xing' => 'xing' ),
        array( 'dustrial-icon fa fa-xing-square' => 'xing-square' ),
        array( 'dustrial-icon fa fa-y-combinator' => 'y-combinator' ),
        array( 'dustrial-icon fa fa-y-combinator-square' => 'y-combinator-square' ),
        array( 'dustrial-icon fa fa-yahoo' => 'yahoo' ),
        array( 'dustrial-icon fa fa-yc' => 'yc' ),
        array( 'dustrial-icon fa fa-yc-square' => 'yc-square' ),
        array( 'dustrial-icon fa fa-yelp' => 'yelp' ),
        array( 'dustrial-icon fa fa-yen' => 'yen' ),
        array( 'dustrial-icon fa fa-yoast' => 'yoast' ),
        array( 'dustrial-icon fa fa-youtube' => 'youtube' ),
        array( 'dustrial-icon fa fa-youtube-play' => 'youtube-play' )
    );
    return array_merge( $icons, $faw4 );
}
add_filter( 'vc_iconpicker-type-fontawesome4', 'dustrial_icon_faw_array' );




/**
 * Register Backend and Frontend CSS Styles
 */
add_action( 'vc_base_register_front_css', 'dustrial_vc_iconpicker_base_register_css' );
add_action( 'vc_base_register_admin_css', 'dustrial_vc_iconpicker_base_register_css' );
function dustrial_vc_iconpicker_base_register_css(){
    wp_register_style('flaticon', get_stylesheet_directory_uri() . '/assets/css/flaticon.css');
}
/**
 * Enqueue Backend and Frontend CSS Styles
 */
add_action( 'vc_backend_editor_enqueue_js_css', 'dustrial_vc_iconpicker_editor_jscss' );
add_action( 'vc_frontend_editor_enqueue_js_css', 'dustrial_vc_iconpicker_editor_jscss' );
function dustrial_vc_iconpicker_editor_jscss(){
    wp_enqueue_style( 'flaticon' );
}
/**
 * Enqueue CSS in Frontend when it's used
 */
add_action('vc_enqueue_font_icon_element', 'dustrial_enqueue_font_flaticon');
function dustrial_enqueue_font_flaticon($font){
    switch ( $font ) {
        case 'flaticon': wp_enqueue_style( 'flaticon' );
    }
}

// Init Visual Composer
if( ! function_exists( 'dustrial_init_vc_shortcodes' ) ) {
  function dustrial_init_vc_shortcodes() {
    if ( defined( 'WPB_VC_VERSION' ) ) {

        /* Set VC editor as default in following post types */
        $list = array(
          'post',
          'page',
          'service',
          'our_project',
        );
        vc_set_default_editor_post_types( $list );
    }
  }

  add_action( 'vc_before_init', 'dustrial_init_vc_shortcodes' );
}